In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
url = "https://raw.githubusercontent.com/PRABHAV-RA2011003011010/Graduate_Admission_Prediction/refs/heads/main/Admission_Predict.csv"
df = pd.read_csv(url)
print(df.head())

   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65  


In [3]:
df.shape

(400, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB


In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.drop(columns=['Serial No.'],inplace=True)

In [7]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [8]:
X=df.iloc[:,0:-1]
Y=df.iloc[:,-1]

In [9]:
X

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [10]:
Y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance of Admit , Length: 400, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [12]:
X_train.shape

(320, 7)

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [14]:
X_train_scaled[0]

array([0.22      , 0.17857143, 0.25      , 0.5       , 0.42857143,
       0.25      , 1.        ])

Covert Numpy arrays to Pytorch tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train.values.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.values.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.values.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.values.astype(np.float32))

In [16]:
y_train_tensor

tensor([0.4400, 0.9500, 0.7100, 0.6200, 0.6400, 0.4700, 0.7300, 0.9600, 0.7100,
        0.7800, 0.5200, 0.7300, 0.8000, 0.8100, 0.5300, 0.6200, 0.7000, 0.7900,
        0.8700, 0.8900, 0.9200, 0.5700, 0.7300, 0.4400, 0.7400, 0.8400, 0.8400,
        0.6400, 0.9000, 0.7400, 0.7100, 0.4700, 0.9000, 0.6300, 0.7500, 0.3800,
        0.7200, 0.8000, 0.8400, 0.8200, 0.4800, 0.6400, 0.6200, 0.7500, 0.7300,
        0.4200, 0.9400, 0.7800, 0.7000, 0.9500, 0.7100, 0.6400, 0.7200, 0.8900,
        0.7000, 0.6800, 0.6400, 0.7700, 0.5700, 0.3400, 0.6100, 0.6700, 0.6100,
        0.8000, 0.6900, 0.5600, 0.6200, 0.4500, 0.8900, 0.6600, 0.7700, 0.9200,
        0.6900, 0.8800, 0.8200, 0.7500, 0.9400, 0.5200, 0.9300, 0.6400, 0.6800,
        0.7100, 0.5600, 0.8100, 0.7000, 0.5300, 0.5700, 0.7300, 0.8700, 0.7000,
        0.4700, 0.8400, 0.8000, 0.9300, 0.8600, 0.8300, 0.6200, 0.7100, 0.9400,
        0.6100, 0.8500, 0.8100, 0.8200, 0.3900, 0.8000, 0.6200, 0.9200, 0.6100,
        0.5200, 0.9100, 0.5400, 0.8500, 

In [17]:
y_train_tensor.shape

torch.Size([320])

Pytorch Starts!!!

In [18]:
#Defining our model using Pytorch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,input_features):
    super().__init__()
    self.layers=nn.Sequential(
        nn.Linear(input_features,out_features=5),
        nn.ReLU(),
        nn.Linear(in_features=5,out_features=1),

    )

  def forward(self,features):
      return self.layers(features)

In [19]:
#Important Parameters
learning_rate = 0.1
epochs = 25
loss_function = nn.MSELoss()

Training Pipeline

In [20]:
model = Model(X_train_tensor.shape[1])
y_pred=model(X_train_tensor)
y_pred

tensor([[ -8.5106],
        [-10.4291],
        [-10.0345],
        [ -9.6401],
        [ -9.2707],
        [ -8.7769],
        [ -9.2410],
        [-10.4383],
        [ -9.4171],
        [-10.0691],
        [ -9.0126],
        [ -9.4250],
        [ -9.9302],
        [ -9.3653],
        [ -8.8492],
        [ -9.4566],
        [ -8.8805],
        [ -9.6157],
        [ -9.3038],
        [ -9.9467],
        [ -9.5270],
        [ -8.7253],
        [ -8.9602],
        [ -8.7412],
        [ -9.5319],
        [ -9.3653],
        [ -9.4343],
        [ -8.8192],
        [-10.0216],
        [ -9.1558],
        [ -9.0134],
        [ -9.0343],
        [-10.4613],
        [ -9.5157],
        [ -9.3347],
        [ -8.2806],
        [ -9.5019],
        [ -9.7015],
        [ -9.4430],
        [ -9.7251],
        [ -9.5235],
        [ -9.0016],
        [ -8.7698],
        [ -9.7062],
        [ -9.6435],
        [ -9.3003],
        [-10.1894],
        [ -9.8074],
        [ -9.7392],
        [-10.2791],


In [32]:
#initialize a model
model = Model(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  y_pred=model(X_train_tensor)
  loss=loss_function(y_pred,y_train_tensor.unsqueeze(1))

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameter update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item():.4f}')




Epoch: 1, Loss: 449.3703
Epoch: 2, Loss: 29483513937920.0000
Epoch: 3, Loss: 1177705250816.0000
Epoch: 4, Loss: 753731502080.0000
Epoch: 5, Loss: 482388148224.0000
Epoch: 6, Loss: 308728365056.0000
Epoch: 7, Loss: 197586141184.0000
Epoch: 8, Loss: 126455136256.0000
Epoch: 9, Loss: 80931299328.0000
Epoch: 10, Loss: 51796029440.0000
Epoch: 11, Loss: 33149458432.0000
Epoch: 12, Loss: 21215653888.0000
Epoch: 13, Loss: 13578019840.0000
Epoch: 14, Loss: 8689932288.0000
Epoch: 15, Loss: 5561556480.0000
Epoch: 16, Loss: 3559396096.0000
Epoch: 17, Loss: 2278013696.0000
Epoch: 18, Loss: 1457928960.0000
Epoch: 19, Loss: 933074560.0000
Epoch: 20, Loss: 597167744.0000
Epoch: 21, Loss: 382187328.0000
Epoch: 22, Loss: 244599888.0000
Epoch: 23, Loss: 156543920.0000
Epoch: 24, Loss: 100188104.0000
Epoch: 25, Loss: 64120392.0000


Model Testing & Evaluation

In [33]:
# model evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    mse = torch.mean((y_pred.squeeze() - y_test_tensor) ** 2)
    rmse = torch.sqrt(mse)
    mae = torch.mean(torch.abs(y_pred.squeeze() - y_test_tensor))

print(f"MSE: {mse.item():.4f}")
print(f"RMSE: {rmse.item():.4f}")
print(f"MAE: {mae.item():.4f}")

MSE: 41036928.0000
RMSE: 6406.0073
MAE: 6406.0073
